const truth={VERIFIED:'verified',OBSERVED:'observed',CALCULATED:'calculated',ESTIMATED:'estimated',DEFINED:'defined',HOLD:'hold','NOT AVAILABLE':'na'};
const modules=[
{code:'C1',title:'Executive Command Center',short:'Command Center',desc:'Vista ejecutiva, gates, evidencia y estado transversal.',state:'DEFINED'},
{code:'C2',title:'FIREWATCH / M00-SAT',short:'FIREWATCH / M00-SAT',desc:'Constelaciones, observaciones, hotspots, escenas, incidentes y evidencia.',state:'HOLD'},
{code:'C3',title:'Territory / M01',short:'Territory / M01',desc:'Territorios, parcelas, rodales, capas GIS y ficha territorial.',state:'DEFINED'},
{code:'C4',title:'Evidence Engine / M02',short:'Evidence Engine / M02',desc:'Procedencia, evidencia individual, SHA-256, timestamps y auditoría local.',state:'VERIFIED'},
{code:'C5',title:'Risk & Priority / M03',short:'Risk & Priority / M03',desc:'Motor explicable R1–R10 preparado para evidencia territorial.',state:'HOLD'},
{code:'C6',title:'Intervention / M04',short:'Intervention / M04',desc:'Cartera de actuaciones vinculada a riesgo, coste y gates.',state:'HOLD'},
{code:'C7',title:'Biomass & Operations',short:'Biomass & Operations',desc:'Biomasa, operaciones, recursos y trazabilidad de ejecución.',state:'DEFINED'},
{code:'C8',title:'Economics & Logistics',short:'Economics & Logistics',desc:'Costes, logística, financiación y escenarios económicos.',state:'DEFINED'},
{code:'C9',title:'MRV & Monitoring / M08',short:'MRV & Monitoring / M08',desc:'Medición, reporte, verificación y evolución temporal.',state:'HOLD'},
{code:'C10',title:'Bioeconomy',short:'Bioeconomy',desc:'Cadenas de valor, circularidad y valorización territorial.',state:'DEFINED'},
{code:'C11',title:'Database & Provenance',short:'Database & Provenance',desc:'Estado de base de datos, conectores y linaje de datos.',state:'HOLD'},
{code:'C12',title:'AI, Security & Assurance / M16',short:'AI / Security / M16',desc:'Gobernanza IA, seguridad defensiva y assurance evaluable.',state:'DEFINED'}];
const moduleData={
C3:{flow:['Territorios','Parcelas','Rodales','Capas','GIS','Ficha territorial'],records:[['TER-001','Pinofranqueado–Las Hurdes','DEFINED','Contexto de proyecto: 3.765,34 ha.'],['TER-DEMO-001','DEMO-100HA-01','DEFINED','Unidad demostrativa de 100 ha.'],['GIS-LAYER-001','Perímetro administrativo','HOLD','Pendiente de geometría administrativa definitiva.'],['GIS-LAYER-002','Severidad / cicatriz','HOLD','Pendiente de evidencia raster/vector validada.']]},
C4:{flow:['Fuente','Ingesta','Provenance','Evidence record','Verificación','Audit trail'],records:[['EVD-SCHEMA-001','Esquema de evidencia individual','VERIFIED','Esquema local activo.'],['EVD-PROV-001','Modelo de procedencia','VERIFIED','Linaje local activo para artefactos incluidos.'],['EVD-HASH-001','Hashes SHA-256 del paquete','VERIFIED','Manifest de integridad local.'],['EVD-AUDIT-001','Registro de auditoría local','VERIFIED','Eventos y gates incluidos.']]},
C5:{flow:['Territorio M01','Evidencia M02','R1–R10','Score','Prioridad','Gate'],records:[['RISK-RULESET-001','Motor R1–R10','DEFINED','Reglas deterministas y explicables; entradas reales pendientes.'],['RISK-DEMO-001','Score DEMO-100HA-01','NOT AVAILABLE','No se calcula sin baseline territorial verificable.'],['RISK-GATE-001','Gate de entrada territorial','HOLD','Exige polígono, capas y evidencia mínima.']]},
C6:{flow:['Riesgo','Alternativas','Actuación','Coste','Evidencia','Aprobación'],records:[['INT-CATALOG-001','Catálogo de actuaciones','DEFINED','Estructura de intervención preparada.'],['INT-DEMO-001','Actuación DEMO-100HA-01','HOLD','No se declara ejecución sin expediente/evidencia.'],['INT-GATE-001','GO / HOLD / NO-GO','DEFINED','Gate formal de decisión humana.']]},
C7:{flow:['Recurso','Operación','Equipo','Logística','Evidencia','Resultado'],records:[['OPS-GRAPH-001','Operations Graph','DEFINED','Relaciones operativas definidas conceptualmente.'],['BIO-INV-001','Inventario de biomasa','HOLD','Pendiente de inventario/LiDAR/campo verificable.'],['OPS-EXEC-001','Ejecución registrada','NOT AVAILABLE','No se declara una operación material ejecutada.']]},
C8:{flow:['Medición','Precio','Coste','Financiador','Anualidad','Certificación'],records:[['ECO-STRUCT-001','Modelo económico territorial','DEFINED','Estructura de costes e ingresos prevista.'],['ECO-REAL-001','Coste ejecutado DEMO','NOT AVAILABLE','Sin certificación de ejecución no existe coste real.'],['LOG-001','Modelo logístico','DEFINED','Preparado para rutas, maquinaria y rendimientos.']]},
C9:{flow:['Baseline','Indicador','Medición','Reporte','Verificación','Evolución'],records:[['MRV-SCHEMA-001','Marco MRV','DEFINED','Modelo de indicadores, evidencias y periodicidad.'],['MRV-BASE-001','Baseline territorial definitivo','HOLD','Debe fijarse antes de reportar cambio.'],['MRV-RESULT-001','Resultado post-intervención','NOT AVAILABLE','No existe resultado sin intervención verificada.']]},
C10:{flow:['Recurso','Transformación','Producto','Mercado','Ingreso','Circularidad'],records:[['BIOECO-MODEL-001','Modelo de cadena de valor','DEFINED','Arquitectura conceptual preparada.'],['BIOECO-MKT-001','Mercado REDBIOMASA','HOLD','No se activa antes de evidencia, territorio y operaciones.'],['BIOECO-REV-001','Ingresos realizados','NOT AVAILABLE','Sin transacciones verificadas.']]},
C11:{flow:['Fuente','Conector','Ingesta','Base de datos','Linaje','Health'],records:[['DB-SCHEMA-001','Esquema de datos FIRECYCLE','DEFINED','Modelo lógico de continuidad.'],['DB-CONN-001','Base PostgreSQL/PostGIS','HOLD','Esta versión estática no declara conexión activa.'],['DB-HEALTH-001','Health check operacional','NOT AVAILABLE','Requiere backend desplegado y verificable.']]},
C12:{flow:['Activo','Riesgo','Control','Evidencia','Assurance','Decisión humana'],records:[['M16-IR-001','Incident Response','DEFINED','Subpanel funcional definido.'],['M16-BC-001','Business Continuity','DEFINED','Subpanel funcional definido.'],['M16-SC-001','Supply-Chain Assurance','DEFINED','Subpanel funcional definido.'],['M16-AI-001','AI Security & Human Oversight','DEFINED','Control de IA y autoridad humana definidos.']]}
};
function badge(s){return `<span class="truth-badge ${truth[s]}">${s}</span>`}
function renderNav(){mainNav.innerHTML=modules.map(m=>`<button class="nav-item" data-code="${m.code}"><span class="nav-code">${m.code}</span><span class="nav-label">${m.short}</span><span class="nav-arrow">›</span></button>`).join('');mainNav.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.code));}
function navigate(c){location.hash=c;render(c)}
function setHeader(c){const m=modules.find(x=>x.code===c)||modules[0];pageTitle.textContent=m.title;breadcrumb.textContent=`FIRECYCLE / ${m.code} / ${m.short}`;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.code===m.code));}
function render(c){if(!modules.some(m=>m.code===c))c='C1';setHeader(c);content.innerHTML=c==='C1'?renderC1():c==='C2'?renderC2():renderModule(c);bindDetails();}
function renderC1(){return `<div class="hero"><section class="hero-card"><span class="eyebrow">C1 · EXECUTIVE COMMAND CENTER</span><h2>De la observación a la decisión verificable</h2><p>FIRECYCLE organiza territorio, evidencia, riesgo, intervención y seguimiento bajo una arquitectura explícita de verdad. M02 mantiene evidencia local verificable; M00-SAT y M01 permanecen sujetos a gates hasta incorporar fuentes operacionales verificables.</p><div class="chain"><span>DATO</span><b>→</b><span>PROCEDENCIA</span><b>→</b><span>EVIDENCIA</span><b>→</b><span>KPI</span><b>→</b><span>GATE</span><b>→</b><span>DECISIÓN</span><b>→</b><span>ACCIÓN</span><b>→</b><span>RESULTADO</span><b>→</b><span>NUEVA EVIDENCIA</span></div></section><section class="hero-card hero-side"><h3>Gates prioritarios</h3><div class="gate-list"><div class="gate-row"><span>Baseline territorial</span>${badge('HOLD')}</div><div class="gate-row"><span>Conectores satelitales</span>${badge('HOLD')}</div><div class="gate-row"><span>Evidence Engine local</span>${badge('VERIFIED')}</div><div class="gate-row"><span>MRV operacional</span>${badge('HOLD')}</div></div></section></div><div class="metrics"><div class="metric"><div class="label">Contexto territorial</div><div class="value">3.765,34 ha</div><div class="note">Dato de proyecto · no equivale a superficie validada GIS</div></div><div class="metric"><div class="label">Unidad demostrativa</div><div class="value">100 ha</div><div class="note">DEMO-100HA-01 · alcance definido</div></div><div class="metric"><div class="label">Módulos C1–C12</div><div class="value">12</div><div class="note">Navegación funcional</div></div><div class="metric"><div class="label">Evidence Engine</div><div class="value">LOCAL VERIFIED</div><div class="note">Sin backend externo</div></div></div>`}
function renderC2(){const c2=FIRECYCLE_DATA.c2;return `<div class="section-head"><div><span class="eyebrow">C2 · FIREWATCH / M00-SAT</span><h2>Cadena satélite → evidencia → decisión</h2><p>Arquitectura funcional profunda sin declarar conectores ni observaciones live no verificadas.</p></div>${badge(c2.gateState)}</div><section class="panel c2-gate"><div><strong>Gate operacional M00-SAT</strong><p>${c2.gateReason}</p></div>${badge('HOLD')}</section><div style="height:16px"></div><section class="panel"><h3>Continuidad M00-SAT</h3><div class="flow-strip">${c2.sections.map((s,i)=>`${i?'<span class="flow-arrow">→</span>':''}<button class="flow-node c2-tab" data-c2="${s.id}">${s.label}</button>`).join('')}</div></section><div style="height:16px"></div><div class="module-grid">${c2.sections.map(s=>`<article class="module-card c2-card" data-c2="${s.id}"><span class="module-code">${s.code}</span><h3>${s.label}</h3><p>${s.description}</p><div class="module-meta"><span>${s.records.length} registro(s)</span>${badge(s.state)}</div></article>`).join('')}</div><div style="height:16px"></div><section id="c2Detail" class="panel">${renderC2Section(c2.sections[0])}</section><div style="height:16px"></div><section class="panel"><h3>Contrato de continuidad</h3><p class="panel-sub">Cada registro satelital deberá poder resolver esta secuencia antes de cambiar de HOLD a OBSERVED/VERIFIED.</p><div class="chain"><span>FUENTE</span><b>→</b><span>OBSERVACIÓN</span><b>→</b><span>PRODUCTO</span><b>→</b><span>CHECKSUM</span><b>→</b><span>EVIDENCIA M02</span><b>→</b><span>KPI</span><b>→</b><span>GATE</span><b>→</b><span>DECISIÓN HUMANA</span></div></section>`}
function renderC2Section(s){return `<div class="section-head"><div><span class="eyebrow">${s.code}</span><h3>${s.label}</h3><p>${s.description}</p></div>${badge(s.state)}</div>${recordsTable(s.records.map(r=>[r.id,r.name,r.state,r.source,`${r.evidence} · KPI: ${r.kpi} · Gate: ${r.gate}`]))}`}
function renderModule(code){const m=modules.find(x=>x.code===code);const d=moduleData[code]||{flow:['Página','Subpágina','Módulo','Submódulo','Registro','Evidencia','KPI','Gate','Decisión'],records:[[`${code}-001`,'Estructura funcional',m.state,m.desc]]};return `<div class="section-head"><div><span class="eyebrow">${m.code} · FIRECYCLE MODULE</span><h2>${m.title}</h2><p>${m.desc}</p></div>${badge(m.state)}</div><section class="panel"><h3>Continuidad funcional</h3><p class="panel-sub">Ningún nodo termina en decoración: cada elemento se proyecta hacia registro y evidencia.</p><div class="flow-strip">${d.flow.map((x,i)=>`${i?'<span class="flow-arrow">→</span>':''}<span class="flow-node">${x}</span>`).join('')}</div></section><div style="height:16px"></div><div class="module-grid">${d.flow.map((x,i)=>`<article class="module-card" data-detail='${JSON.stringify({module:code,stage:x,index:i}).replaceAll("'","&#39;")}'><span class="module-code">${code}.${String(i+1).padStart(2,'0')}</span><h3>${x}</h3><p>Vista funcional de ${x.toLowerCase()} con continuidad hacia procedencia, evidencia, KPI, gate y decisión.</p><div class="module-meta"><span>Continuidad activa</span>${badge(i<2?'DEFINED':m.state)}</div></article>`).join('')}</div><div style="height:16px"></div><section class="panel"><h3>Registros y evidencia</h3><p class="panel-sub">Los registros sin fuente operacional suficiente permanecen en HOLD o NOT AVAILABLE.</p>${recordsTable(d.records.map(r=>[r[0],r[1],r[2],code,r[3]]))}</section>${code==='C4'?renderEvidenceManifest():''}`}
function recordsTable(rows){return `<div class="table-wrap"><table><thead><tr><th>ID</th><th>Registro</th><th>Estado</th><th>Origen / módulo</th><th>Evidencia / condición</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="record-link" data-record="${r[0]}">${r[0]}</button></td><td>${r[1]}</td><td>${badge(r[2])}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('')}</tbody></table></div>`}
function renderEvidenceManifest(){const rows=(FIRECYCLE_DATA.evidenceManifest||[]).map(e=>`<tr><td><button class="record-link" data-evidence-id="${e.id}">${e.id}</button></td><td>${e.file}</td><td>${badge(e.state)}</td><td><code>${e.sha256}</code></td><td>${e.provenance}</td></tr>`).join('');return `<div style="height:16px"></div><section class="panel"><div class="section-head"><div><h3>Manifest de integridad</h3><p>Artefactos locales con control de integridad.</p></div>${badge('VERIFIED')}</div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Archivo</th><th>Estado</th><th>SHA-256</th><th>Procedencia</th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function bindDetails(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelectorAll('[data-detail]').forEach(c=>c.onclick=()=>{const d=JSON.parse(c.dataset.detail);openDetail(`${d.module}.${String(d.index+1).padStart(2,'0')}`,d.stage,'DEFINED','Submódulo funcional demostrativo.');});document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>openRecordDetail(b.dataset.record));document.querySelectorAll('[data-evidence-id]').forEach(b=>b.onclick=()=>openEvidenceDetail(b.dataset.evidenceId));document.querySelectorAll('[data-c2]').forEach(b=>b.onclick=()=>{const s=FIRECYCLE_DATA.c2.sections.find(x=>x.id===b.dataset.c2);const target=document.getElementById('c2Detail');if(target){target.innerHTML=renderC2Section(s);target.scrollIntoView({behavior:'smooth',block:'start'});bindDetails();}});}
function openRecordDetail(id){let sat=null;for(const s of FIRECYCLE_DATA.c2?.sections||[]){sat=s.records.find(r=>r.id===id);if(sat)break}if(sat){openDetail(id,sat.name,sat.state,`${sat.evidence} | Source: ${sat.source} | KPI: ${sat.kpi} | Gate: ${sat.gate}`);return}const ev=(FIRECYCLE_DATA.recordEvidence||{})[id];if(ev)openDetail(id,ev.title,ev.state,`${ev.note} | Evidence: ${ev.evidenceId} | Source: ${ev.source}`);else openDetail(id,'Registro FIRECYCLE','DEFINED','El estado mostrado pertenece a esta interfaz y no sustituye evidencia operacional externa.');}
function openEvidenceDetail(id){const ev=(FIRECYCLE_DATA.evidenceManifest||[]).find(x=>x.id===id);if(!ev)return;dialogContent.innerHTML=`<span class="eyebrow">M02 / EVIDENCIA LOCAL</span><h2>${ev.file}</h2>${badge(ev.state)}<div class="detail-kv"><div>ID</div><div>${ev.id}</div><div>SHA-256</div><div><code>${ev.sha256}</code></div><div>Procedencia</div><div>${ev.provenance}</div></div>`;detailDialog.showModal();}
function openDetail(id,title,state,note){dialogContent.innerHTML=`<span class="eyebrow">REGISTRO → EVIDENCIA → KPI → GATE → DECISIÓN</span><h2>${title}</h2>${badge(state)}<div class="detail-kv"><div>ID</div><div>${id}</div><div>Procedencia</div><div>FIRECYCLE Command Center</div><div>Evidencia</div><div>${note}</div><div>Gate</div><div>${state==='VERIFIED'?'GO limitado al alcance verificado':'HOLD cuando dependa de datos externos no conectados'}</div><div>Decisión</div><div>Reservada a autoridad humana con evidencia suficiente</div></div>`;detailDialog.showModal();}
truthLegendBtn.onclick=()=>truthLegend.classList.toggle('hidden');closeDialog.onclick=()=>detailDialog.close();detailDialog.onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};window.addEventListener('hashchange',()=>render(location.hash.slice(1)||'C1'));renderNav();render(location.hash.slice(1)||'C1');