(() => {
  const state={healthy:false,projects:[],selectedProject:null}; const $=id=>document.getElementById(id);
  async function jsonFetch(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok && r.status!==207)throw new Error(b.message||b.error||`HTTP ${r.status}`);return b;}
  function status(text,kind=''){const el=$('forgeStatus');if(el){el.textContent=text;el.className=`forge-status ${kind}`;}}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function renderProjects(){const s=$('forgeProjectSelect');if(!s)return;s.innerHTML=state.projects.length?state.projects.map(p=>`<option value="${p.id}">${escapeHtml(p.name)} · ${escapeHtml(p.slug)}</option>`).join(''):'<option value="">No projects yet</option>';if(state.selectedProject)s.value=state.selectedProject;$('forgeRunBtn').disabled=!state.healthy||!state.projects.length;}
  async function health(){try{const r=await jsonFetch('/api/health');state.healthy=r.ok===true;$('forgeHealth').textContent=state.healthy?'DATABASE CONNECTED':(r.status||'DATABASE NOT READY');$('forgeHealth').className=`forge-pill ${state.healthy?'ok':''}`;}catch(e){state.healthy=false;$('forgeHealth').textContent='DATABASE NOT CONNECTED';$('forgeHealth').className='forge-pill';}renderProjects();}
  async function loadProjects(){try{const r=await jsonFetch('/api/projects');state.projects=r.projects||[];if(!state.selectedProject&&state.projects[0])state.selectedProject=state.projects[0].id;renderProjects();}catch(e){state.projects=[];renderProjects();status(`No se pudieron cargar los proyectos: ${e.message}`,'error');}}
  function openNewProject(){$('forgeModal').showModal();$('forgeName').focus();}
  async function createProject(e){e.preventDefault();const name=$('forgeName').value.trim(),description=$('forgeDescription').value.trim();if(!name)return;try{$('forgeCreateBtn').disabled=true;status('CREATE PROJECT · persistiendo en PostgreSQL…');const r=await jsonFetch('/api/projects',{method:'POST',body:JSON.stringify({name,description})});state.projects.unshift(r.project);state.selectedProject=r.project.id;$('forgeModal').close();$('forgeName').value='';$('forgeDescription').value='';renderProjects();status(`Proyecto creado: ${r.project.name}`,'ok');}catch(e){status(`CREATE PROJECT falló: ${e.message}`,'error');}finally{$('forgeCreateBtn').disabled=false;}}
  async function runDiscovery(){const projectId=$('forgeProjectSelect').value;if(!projectId)return status('Selecciona un proyecto.','error');try{$('forgeRunBtn').disabled=true;status('RUN DISCOVERY · ejecutando AI + web research + Evidence Engine…');const r=await jsonFetch('/api/discovery',{method:'POST',body:JSON.stringify({project_id:projectId,objective:$('forgeObjective').value.trim()||'Initial operational discovery'})});const ok=r.ok===true;status(ok?`RUN DISCOVERY completado · ${r.agents?.filter(a=>a.status==='COMPLETED').length||0}/${r.agents?.length||0} agentes ejecutados.`:`RUN DISCOVERY terminó con fallos · revisa la trazabilidad.` ,ok?'ok':'error');renderRun(r);}catch(e){status(`RUN DISCOVERY falló: ${e.message}`,'error');}finally{renderProjects();}}
  function renderRun(r){const t=$('forgeResults');if(!t)return;t.innerHTML=`<div class="forge-panel"><strong>Última ejecución · ${escapeHtml(r.run?.status||'UNKNOWN')}</strong><div class="forge-runs"><div class="forge-run"><code>${escapeHtml(r.run?.id||'')}</code><p>${escapeHtml(r.synthesis?.summary||'Synthesis not available.')}</p></div></div><div class="forge-grid">${(r.agents||[]).map(a=>`<div class="forge-agent"><strong>${escapeHtml(a.agent_key)}</strong><small>${escapeHtml(a.status)}${a.evidence_count!=null?' · evidence '+escapeHtml(a.evidence_count):''}${a.confidence!=null?' · confidence '+escapeHtml(a.confidence):''}</small></div>`).join('')}</div></div>`;}
  function injectUI(){const top=document.querySelector('.top-actions');if(!top||$('forgeOpenBtn'))return;top.insertAdjacentHTML('afterbegin','<button id="forgeOpenBtn" class="ghost-btn">NEW PROJECT</button>');const content=document.querySelector('.content');if(content)content.insertAdjacentHTML('afterbegin',`<section class="forge-bar"><strong>PROJECT FORGE · Discovery Command Center</strong><span id="forgeHealth" class="forge-pill">CHECKING DATABASE…</span><select id="forgeProjectSelect" class="forge-btn" aria-label="Project"></select><button id="forgeRunBtn" class="forge-btn primary">RUN DISCOVERY</button></section><section class="forge-panel"><label>Discovery objective <input id="forgeObjective" style="width:100%;margin-top:8px;box-sizing:border-box" value="Initial operational discovery" /></label><div id="forgeStatus" class="forge-status">Waiting for infrastructure health.</div></section><div id="forgeResults" style="margin-top:16px"></div>`);document.body.insertAdjacentHTML('beforeend',`<dialog id="forgeModal" class="forge-modal"><h2>NEW PROJECT</h2><form id="forgeForm" class="forge-form"><label>Project name<input id="forgeName" required maxlength="200" placeholder="PROJECT FORGE / Demo Project" /></label><label>Description<textarea id="forgeDescription" placeholder="Operational scope, objectives and context"></textarea></label><div class="forge-actions"><button type="button" id="forgeCancelBtn" class="forge-btn">CANCEL</button><button id="forgeCreateBtn" class="forge-btn primary" type="submit">CREATE PROJECT</button></div></form></dialog>`);$('forgeOpenBtn').onclick=openNewProject;$('forgeCancelBtn').onclick=()=>$('forgeModal').close();$('forgeForm').onsubmit=createProject;$('forgeRunBtn').onclick=runDiscovery;$('forgeProjectSelect').onchange=e=>{state.selectedProject=e.target.value;};}
  window.addEventListener('DOMContentLoaded',async()=>{injectUI();await health();await loadProjects();});
})();
