(()=>{
const STAC_ROOT='https://stac.dataspace.copernicus.eu/v1';
const SEARCH=`${STAC_ROOT}/search`;
const COLLECTION='sentinel-2-l2a';
// Discovery AOI only. This is deliberately broader than DEMO-100HA-01 and is not a verified project polygon.
const DISCOVERY_BBOX=[-6.50,40.20,-6.20,40.45];
const WINDOWS={pre:['2026-08-08T00:00:00Z','2026-08-17T23:59:59Z'],post:['2026-08-21T00:00:00Z','2026-08-31T23:59:59Z']};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function stateBadge(s){return typeof badge==='function'?badge(s):`<span>${esc(s)}</span>`}
function panel(){return `<section id="stacPanel" class="panel" style="margin-top:16px"><div class="section-head"><div><span class="eyebrow">C3 v1.5 · REAL EO BASELINE</span><h3>Copernicus STAC · Sentinel-2 L2A</h3><p>Consulta de metadatos EO reales sobre una AOI de descubrimiento alrededor de Pinofranqueado. El resultado no valida por sí solo el perímetro DEMO ni el baseline M01.</p></div>${stateBadge('DEFINED')}</div><div class="visual-chain"><span>STAC</span><b>→</b><span>ITEM</span><b>→</b><span>ASSETS</span><b>→</b><span>B08/B12</span><b>→</b><span>NBR</span><b>→</b><span>dNBR</span><b>→</b><span>M02</span></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin:14px 0"><button class="ghost-btn" data-stac-window="pre">Buscar PRE 08–17/08/2026</button><button class="ghost-btn" data-stac-window="post">Buscar POST 21–31/08/2026</button><a class="ghost-btn" href="https://stac.dataspace.copernicus.eu/v1/api.html" target="_blank" rel="noopener">Swagger STAC</a></div><div id="stacStatus" class="visual-note">Estado: preparado para consulta pública de metadatos. AOI discovery bbox: ${DISCOVERY_BBOX.join(', ')}.</div><div id="stacResults" style="margin-top:12px"></div></section>`}
function mount(){if((location.hash||'#C1').slice(1).toUpperCase()!=='C3')return;const c=document.getElementById('content');if(!c||document.getElementById('stacPanel'))return;c.insertAdjacentHTML('beforeend',panel());bind();}
function bind(){document.querySelectorAll('[data-stac-window]').forEach(b=>b.onclick=()=>searchWindow(b.dataset.stacWindow));}
async function searchWindow(kind){const status=document.getElementById('stacStatus'),out=document.getElementById('stacResults');const w=WINDOWS[kind];if(!w)return;status.innerHTML=`Consultando ${esc(COLLECTION)} · ${esc(w[0])} → ${esc(w[1])}…`;out.innerHTML='';const payload={collections:[COLLECTION],bbox:DISCOVERY_BBOX,datetime:`${w[0]}/${w[1]}`,limit:10,query:{'eo:cloud_cover':{lte:80}},sortby:[{field:'properties.eo:cloud_cover',direction:'asc'},{field:'properties.datetime',direction:'asc'}]};try{const r=await fetch(SEARCH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();const items=j.features||[];status.innerHTML=`${stateBadge(items.length?'OBSERVED':'NOT AVAILABLE')} ${items.length} item(s) devueltos por CDSE STAC para ventana ${kind.toUpperCase()}.`;out.innerHTML=items.length?render(items,kind):'<p class="panel-sub">No se devolvieron items para esta ventana/AOI.</p>';}catch(e){status.innerHTML=`${stateBadge('HOLD')} La consulta desde GitHub Pages no pudo completarse (${esc(e.message)}). Se mantiene el gate; use Swagger/CDSE o un backend proxy si el navegador bloquea CORS.`;}}
function assetKeys(i){const a=i.assets||{};return ['B08_10m','B08_20m','B08','B12_20m','B12','visual','thumbnail'].filter(k=>a[k]);}
function render(items,kind){return `<div class="table-wrap"><table><thead><tr><th>PRODUCT / ITEM ID</th><th>Adquisición</th><th>Nubes</th><th>Plataforma</th><th>MGRS/Tile</th><th>Assets relevantes</th><th>M02</th></tr></thead><tbody>${items.map((i,n)=>{const p=i.properties||{};const id=i.id||'NOT AVAILABLE';const evid=`EVD-EO-S2-${kind.toUpperCase()}-${String(n+1).padStart(3,'0')}`;return `<tr><td><button class="record-link" data-stac-item="${esc(id)}">${esc(id)}</button></td><td>${esc(p.datetime||p.start_datetime||'NOT AVAILABLE')}</td><td>${esc(p['eo:cloud_cover']??'NOT AVAILABLE')}%</td><td>${esc(p.platform||p.constellation||'Sentinel-2')}</td><td>${esc(p['s2:mgrs_tile']||p['mgrs:utm_zone']||'NOT AVAILABLE')}</td><td>${esc(assetKeys(i).join(', ')||'Consultar item')}</td><td>${stateBadge('OBSERVED')}<br><small>${evid}</small></td></tr>`}).join('')}</tbody></table></div><div class="visual-note">OBSERVED significa que el catálogo devolvió metadatos reales. VERIFIED requerirá conservar el item/artefacto, checksum, AOI, bandas y vínculo M02 reproducible.</div>`}
const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(c){oldRender(c);setTimeout(mount,0)}}
window.addEventListener('hashchange',()=>setTimeout(mount,0));
setTimeout(mount,0);
window.FIRECYCLE_STAC={root:STAC_ROOT,collection:COLLECTION,bbox:DISCOVERY_BBOX,windows:WINDOWS,searchWindow};
})();