(()=>{
const STAC_ROOT='https://stac.dataspace.copernicus.eu/v1';
const SEARCH=`${STAC_ROOT}/search`;
const COLLECTION='sentinel-2-l2a';
const DISCOVERY_BBOX=[-6.50,40.20,-6.20,40.45];
const WINDOWS={pre:['2026-08-08T00:00:00Z','2026-08-17T23:59:59Z'],post:['2026-08-21T00:00:00Z','2026-08-31T23:59:59Z']};
const TARGET={pre:'2026-08-17T23:59:59Z',post:'2026-08-21T00:00:00Z'};
const selected={pre:null,post:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function stateBadge(s){return typeof badge==='function'?badge(s):`<span>${esc(s)}</span>`}
function panel(){return `<section id="stacPanel" class="panel" style="margin-top:16px"><div class="section-head"><div><span class="eyebrow">C3 v1.5 · REAL EO BASELINE</span><h3>Copernicus STAC · Sentinel-2 L2A</h3><p>Descubrimiento, selección reproducible PRE/POST y preparación del pipeline NBR/dNBR. La AOI sigue siendo de descubrimiento y no sustituye el polígono DEMO validado.</p></div>${stateBadge('DEFINED')}</div><div class="visual-chain"><span>STAC</span><b>→</b><span>ITEM</span><b>→</b><span>B08/B12</span><b>→</b><span>NBR PRE</span><b>→</b><span>NBR POST</span><b>→</b><span>dNBR</span><b>→</b><span>SEVERIDAD</span><b>→</b><span>M02</span></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin:14px 0"><button class="ghost-btn" data-stac-auto="1">Selección automática PRE + POST</button><button class="ghost-btn" data-stac-window="pre">Buscar PRE</button><button class="ghost-btn" data-stac-window="post">Buscar POST</button><a class="ghost-btn" href="https://stac.dataspace.copernicus.eu/v1/api.html" target="_blank" rel="noopener">Swagger STAC</a></div><div id="stacStatus" class="visual-note">Preparado. Criterio: menor nubosidad + proximidad temporal al incendio, con assets B08/B12 requeridos para cálculo.</div><div id="stacResults" style="margin-top:12px"></div><div id="dnbrPipeline" style="margin-top:12px"></div></section>`}
function mount(){if((location.hash||'#C1').slice(1).toUpperCase()!=='C3')return;const c=document.getElementById('content');if(!c||document.getElementById('stacPanel'))return;c.insertAdjacentHTML('beforeend',panel());bind();}
function bind(){document.querySelectorAll('[data-stac-window]').forEach(b=>b.onclick=()=>searchWindow(b.dataset.stacWindow,true));const a=document.querySelector('[data-stac-auto]');if(a)a.onclick=autoSelect;}
function payload(kind){const w=WINDOWS[kind];return {collections:[COLLECTION],bbox:DISCOVERY_BBOX,datetime:`${w[0]}/${w[1]}`,limit:25,query:{'eo:cloud_cover':{lte:80}},sortby:[{field:'properties.eo:cloud_cover',direction:'asc'},{field:'properties.datetime',direction:'asc'}]};}
async function fetchItems(kind){const r=await fetch(SEARCH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(kind))});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();return j.features||[];}
function findAsset(item,candidates){const a=item.assets||{};for(const key of candidates){if(a[key])return {key,href:a[key].href||'',type:a[key].type||'',roles:a[key].roles||[]};}const keys=Object.keys(a);for(const key of keys){const u=key.toUpperCase();if(candidates.some(c=>u.includes(c.replace('_10M','').replace('_20M',''))))return {key,href:a[key].href||'',type:a[key].type||'',roles:a[key].roles||[]};}return null;}
function assets(item){return {b08:findAsset(item,['B08_10m','B08_20m','B08']),b12:findAsset(item,['B12_20m','B12']),scl:findAsset(item,['SCL_20m','SCL']),visual:findAsset(item,['visual','thumbnail'])};}
function dateMs(item){return Date.parse(item.properties?.datetime||item.properties?.start_datetime||0)||0;}
function cloud(item){const v=Number(item.properties?.['eo:cloud_cover']);return Number.isFinite(v)?v:100;}
function score(item,kind){const target=Date.parse(TARGET[kind]);const days=Math.abs(dateMs(item)-target)/86400000;const a=assets(item);const assetPenalty=(a.b08&&a.b12)?0:1000;return cloud(item)*5+days+assetPenalty;}
function choose(items,kind){return [...items].sort((a,b)=>score(a,kind)-score(b,kind))[0]||null;}
async function searchWindow(kind,show=true){const status=document.getElementById('stacStatus'),out=document.getElementById('stacResults');status.innerHTML=`Consultando ${kind.toUpperCase()}…`;try{const items=await fetchItems(kind);const best=choose(items,kind);selected[kind]=best;if(show)out.innerHTML=render(items,kind,best);status.innerHTML=`${stateBadge(items.length?'OBSERVED':'NOT AVAILABLE')} ${items.length} item(s) encontrados. ${best?`Mejor candidato ${kind.toUpperCase()}: <strong>${esc(best.id)}</strong>.`:''}`;renderPipeline();return {items,best};}catch(e){status.innerHTML=`${stateBadge('HOLD')} Consulta STAC no completada (${esc(e.message)}).`;return {items:[],best:null};}}
async function autoSelect(){const status=document.getElementById('stacStatus');status.innerHTML='Consultando PRE y POST y aplicando selección reproducible…';const [pre,post]=await Promise.all([searchWindow('pre',false),searchWindow('post',false)]);const out=document.getElementById('stacResults');out.innerHTML=`<div class="grid-2"><section class="panel"><h3>PRE seleccionado</h3>${selectedCard(pre.best,'pre')}</section><section class="panel"><h3>POST seleccionado</h3>${selectedCard(post.best,'post')}</section></div>`;if(pre.best&&post.best)status.innerHTML=`${stateBadge('OBSERVED')} Pareja PRE/POST seleccionada automáticamente. El cálculo raster permanece HOLD hasta disponer de acceso reproducible a B08/B12 y AOI validada.`;renderPipeline();}
function selectedCard(i,kind){if(!i)return `<p>${stateBadge('NOT AVAILABLE')} Sin candidato.</p>`;const p=i.properties||{},a=assets(i);return `<p><strong>${esc(i.id)}</strong></p><p class="panel-sub">${esc(p.datetime||'NOT AVAILABLE')} · nubes ${esc(p['eo:cloud_cover']??'NA')}%</p><div class="gate-list"><div class="gate-row"><span>B08</span>${stateBadge(a.b08?'OBSERVED':'HOLD')}</div><div class="gate-row"><span>B12</span>${stateBadge(a.b12?'OBSERVED':'HOLD')}</div><div class="gate-row"><span>SCL</span>${stateBadge(a.scl?'OBSERVED':'DEFINED')}</div><div class="gate-row"><span>M02 ID</span><small>EVD-EO-S2-${kind.toUpperCase()}-001</small></div></div>`;}
function render(items,kind,best){return `<div class="table-wrap"><table><thead><tr><th>Selección</th><th>PRODUCT / ITEM ID</th><th>Adquisición</th><th>Nubes</th><th>B08</th><th>B12</th><th>M02</th></tr></thead><tbody>${items.map((i,n)=>{const p=i.properties||{},a=assets(i),isBest=best&&i.id===best.id,evid=`EVD-EO-S2-${kind.toUpperCase()}-${String(n+1).padStart(3,'0')}`;return `<tr><td>${isBest?'<strong>★ AUTO</strong>':''}</td><td>${esc(i.id||'NA')}</td><td>${esc(p.datetime||'NA')}</td><td>${esc(p['eo:cloud_cover']??'NA')}%</td><td>${a.b08?esc(a.b08.key):'NO'}</td><td>${a.b12?esc(a.b12.key):'NO'}</td><td>${stateBadge('OBSERVED')}<br><small>${evid}</small></td></tr>`}).join('')}</tbody></table></div>`;}
function renderPipeline(){const el=document.getElementById('dnbrPipeline');if(!el)return;const pre=selected.pre,post=selected.post;if(!pre||!post){el.innerHTML='';return;}const ap=assets(pre),ao=assets(post);const ready=!!(ap.b08&&ap.b12&&ao.b08&&ao.b12);el.innerHTML=`<section class="panel"><div class="section-head"><div><span class="eyebrow">PIPELINE EO</span><h3>NBR PRE → NBR POST → dNBR → severidad</h3><p>Fórmula: NBR=(B08−B12)/(B08+B12); dNBR=NBRpre−NBRpost.</p></div>${stateBadge(ready?'DEFINED':'HOLD')}</div><div class="gate-list"><div class="gate-row"><span>PRE item + B08/B12</span>${stateBadge(ap.b08&&ap.b12?'OBSERVED':'HOLD')}</div><div class="gate-row"><span>POST item + B08/B12</span>${stateBadge(ao.b08&&ao.b12?'OBSERVED':'HOLD')}</div><div class="gate-row"><span>AOI DEMO-100HA-01 validada</span>${stateBadge('HOLD')}</div><div class="gate-row"><span>Máscara SCL/nubes aplicada</span>${stateBadge('HOLD')}</div><div class="gate-row"><span>Raster NBR PRE</span>${stateBadge('NOT AVAILABLE')}</div><div class="gate-row"><span>Raster NBR POST</span>${stateBadge('NOT AVAILABLE')}</div><div class="gate-row"><span>Raster dNBR</span>${stateBadge('NOT AVAILABLE')}</div><div class="gate-row"><span>EVD-EO-DNBR-001</span>${stateBadge('HOLD')}</div></div><div class="visual-note">GitHub Pages puede descubrir y seleccionar metadatos STAC, pero no debe declarar CALCULATED hasta ejecutar el procesamiento raster sobre assets accesibles, aplicar máscara de nubes, armonizar resolución B08/B12 y conservar artefactos + checksum en M02.</div></section>`;}
const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(c){oldRender(c);setTimeout(mount,0)}}
window.addEventListener('hashchange',()=>setTimeout(mount,0));setTimeout(mount,0);
window.FIRECYCLE_STAC={root:STAC_ROOT,collection:COLLECTION,bbox:DISCOVERY_BBOX,windows:WINDOWS,searchWindow,autoSelect,selected,assets};
})();